---
Name: summitapi
After: 'framework/*','cms/*', 'mysite/*'
---
Injector:
  SummitAddOnRepository:
    class: SapphireSummitAddOnRepository
  SummitPackageRepository:
    class: SapphireSummitPackageRepository
  PackagePurchaseOrderRepository:
    class: SapphirePackagePurchaseOrderRepository
  SummitPackagePurchaseOrderFactory:
    class: SapphireSummitPackagePurchaseOrderFactory
  SummitPackagePurchaseOrderManager:
    constructor:
      0: '%$PackagePurchaseOrderRepository'
      1: '%$SummitPackageRepository'
      2: '%$SummitPackagePurchaseOrderFactory'
      3: '%$TransactionManager'
  SummitsApi:
    constructor:
      0: '%$SummitPackageRepository'
      1: '%$SummitAddOnRepository'
      2: '%$SummitPackagePurchaseOrderManager'

SummitSponsorPage_Controller:
  dependencies:
    PackagePurchaseOrderManager: '%$SummitPackagePurchaseOrderManager'

SangriaPageSummitSponsorshipPurchaseOrderExtension:
  dependencies:
    PackagesRepository: "%$PackagePurchaseOrderRepository"

SangriaPage_Controller:
  extensions:
    - SangriaPageSummitSponsorshipPurchaseOrderExtension

Member:
  extensions:
    - PresentationMemberExtension
    - MemberTokenProvider
MemberTokenProvider:
  token_expire: 3600
Director:
  rules:
    'presentations/api/v1': 'PresentationAPI'
    'presentations/authenticate': 'PresentationAPITokenGenerator'
    'summit-login': 'SummitSecurity'
PresentationCategory:
  extensions:
    - JSONable
PresentationSpeaker:
  extensions:
    - JSONable
PresentationTopic:
  extensions:
    - JSONable
Summit:
  extensions:
    - JSONable
Presentation:
  extensions:
    - Sluggable
    - JSONable
  status_options:
    - Received
    - In community voting
    - Being reviewed by track chairs
    - accepted
    - not accepted
    - accepted as an alternate
SchedPresentation:
  extensions:
    - Sluggable
BootstrapMemberLoginForm:
  extensions:
    - BootstrapLoginFormExtension