---
Name: summitmodule
After: 'framework/*','cms/*', 'mysite/*'
---
Member:
  extensions:
    - PresentationMemberExtension
    - MemberTokenProvider
    - AttendeeMember
EditProfilePage_Controller:
  extensions:
    - EditProfilePageSummitAttendeeExtension
MemberTokenProvider:
  token_expire: 500000
PresentationCategory:
  extensions:
    - JSONable
    - SummitEntity
PresentationSpeaker:
  extensions:
    - JSONable
    - SummitEntity
PresentationTopic:
  extensions:
    - JSONable
    - SummitEntity
SummitPresentationComment:
  extensions:
    - JSONable
Summit:
  extensions:
    - JSONable
    - SummitEntity
SummitTrackChair:
  extensions:
    - JSONable
    - SummitEntity
SummitCategoryChange:
  extensions:
    - JSONable    
Presentation:
  extensions:
    - Sluggable
    - JSONable
    - SummitEntity
  status_options:
    - Received
    - In community voting
    - Being reviewed by track chairs
    - accepted
    - not accepted
    - accepted as an alternate
BootstrapMemberLoginForm:
  extensions:
    - BootstrapLoginFormExtension
SummitAttendee:
  extensions:
    - SummitEntity
SummitEvent:
  extensions:
    - SummitEntity
SummitEventFeedback:
  extensions:
    - SummitEntity
SummitEventType:
  extensions:
    - SummitEntity
PresentationMaterial:
  extensions:
    - SummitEntity
SummitAbstractLocation:
  extensions:
    - SummitEntity
SummitType:
  extensions:
    - SummitEntity
SummitTicketType:
  extensions:
    - SummitEntity