---
Name: eventsroutes
After: 'framework/routes#coreroutes'
---
Director:
  rules:
    'api/v1/event-registration-requests': 'EventRegistrationRequestCrudApi'
    'api/v1/events': 'EventCrudApi'
    'api/v1/events-types': 'EventTypeApi'
    'event-registration-requests': 'EventRegistrationRequestController'