---
Name: database_config
After: 'framework/*','cms/*', 'openstack/*'
---
Distribution:
  extensions:
    - MandatoryDataObject
Appliance:
  extensions:
    - MandatoryDataObject
Consultant:
  extensions:
    - MandatoryDataObject
PrivateCloudService:
  extensions:
    - MandatoryDataObject
PublicCloudService:
  extensions:
    - MandatoryDataObject
RemoteCloudService:
  extensions:
    - MandatoryDataObject
RSVPTextBoxQuestionTemplate:
  extensions:
    - MandatoryDataObject
RSVPTextAreaQuestionTemplate:
  extensions:
    - MandatoryDataObject
RSVPMemberEmailQuestionTemplate:
  extensions:
    - MandatoryDataObject
RSVPMemberFirstNameQuestionTemplate:
  extensions:
    - MandatoryDataObject
RSVPMemberLastNameQuestionTemplate:
  extensions:
    - MandatoryDataObject
RSVPCheckBoxListQuestionTemplate:
  extensions:
    - MandatoryDataObject
RSVPRadioButtonListQuestionTemplate:
  extensions:
    - MandatoryDataObject
